apiVersion: v1
kind: Pod
metadata:
  name: frontend
  labels:
    module: frontend
spec:
  containers:
    - name: frontend
      image: hello-world-frontend
      imagePullPolicy: IfNotPresent
      ports:
        - containerPort: 80
