version: "3.8"

services:
  frontend:
    build: frontend
    ports:
      - 80:80
    volumes:
      - ./frontend:/frontend/
    networks:
      - frontend-network

  backend:
    build: backend
    volumes:
      - ./backend:/backend/
    networks:
      - frontend-network
      - db-network

  db:
    image: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: secret
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - db-network

  adminer:
    image: adminer
    restart: always
    ports:
      - 8090:8080
    networks:
      - db-network

volumes:
  db_data:

networks:
  db-network:
    driver: bridge

  frontend-network:
    driver: bridge
