version: "3.8"

services:
  frontend:
    build: frontend
    ports:
      - 80:80
    volumes:
      - ./frontend:/frontend/

  backend:
    build: backend
    ports:
      - 8081:80
    volumes:
      - ./backend:/backend/

  db:
    image: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: secret
    volumes:
      - db_data:/var/lib/mysql

  adminer:
    image: adminer
    restart: always
    ports:
      - 8090:8080

volumes:
  db_data:
